In [79]:
from torchvision import datasets
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib
import scipy

# mnist

In [3]:
mnist_train = datasets.MNIST('/tmp', train=True, transform=None, target_transform=None, download=True)

Extracting /tmp/MNIST/raw/train-images-idx3-ubyte.gz to /tmp/MNIST/raw


Extracting /tmp/MNIST/raw/train-labels-idx1-ubyte.gz to /tmp/MNIST/raw



Extracting /tmp/MNIST/raw/t10k-images-idx3-ubyte.gz to /tmp/MNIST/raw


Extracting /tmp/MNIST/raw/t10k-labels-idx1-ubyte.gz to /tmp/MNIST/raw
Processing...
Done!


In [4]:
mnist_test = datasets.MNIST('/tmp', train=False, transform=None, target_transform=None, download=True)

In [11]:
np.unique(mnist_train.targets, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949]))

In [73]:
np.unique(mnist_train.targets, return_counts=True)[1] / np.unique(mnist_train.targets, return_counts=True)[1].sum()

array([0.09871667, 0.11236667, 0.0993    , 0.10218333, 0.09736667,
       0.09035   , 0.09863333, 0.10441667, 0.09751667, 0.09915   ])

In [12]:
np.unique(mnist_test.targets, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 980, 1135, 1032, 1010,  982,  892,  958, 1028,  974, 1009]))

## pick subset

In [70]:
linear_ratio = np.array(range(1,11))
linear_ratio = linear_ratio / linear_ratio.max()
stats = np.unique(mnist_test.targets, return_counts=True)[1]
subset = stats.min() * linear_ratio
subset = subset.astype(int)

In [71]:
subset

array([ 89, 178, 267, 356, 446, 535, 624, 713, 802, 892])

In [72]:
sum(subset)

4902

### severe imbalance

In [92]:
num_of_class = 10
alpha=0.01
x = np.linspace(1, 5, num_of_class)
target = scipy.stats.genpareto.pdf(x, alpha).tolist()
severe_ratio = np.array([t/sum(target) for t in target])
severe_ratio = severe_ratio / max(severe_ratio)
stats = np.unique(mnist_train.targets, return_counts=True)[1]
subset = stats.min() * severe_ratio
subset = np.flip(subset.astype(int))

In [93]:
subset

array([ 107,  164,  253,  389,  601,  930, 1441, 2237, 3479, 5421])

# svhn

In [5]:
svhn_train = datasets.SVHN('/tmp', split='train', transform=None, target_transform=None, download=True)

In [6]:
svhn_test = datasets.SVHN('/tmp', split='test', transform=None, target_transform=None, download=True)

In [14]:
np.unique(svhn_train.labels, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 4948, 13861, 10585,  8497,  7458,  6882,  5727,  5595,  5045,
         4659]))

In [15]:
np.unique(svhn_test.labels, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1744, 5099, 4149, 2882, 2523, 2384, 1977, 2019, 1660, 1595]))

In [75]:
np.unique(svhn_test.labels, return_counts=True)[1] / np.unique(svhn_test.labels, return_counts=True)[1].sum()

array([0.06699447, 0.19587431, 0.15938076, 0.1107099 , 0.09691918,
       0.09157959, 0.07594499, 0.07755839, 0.06376767, 0.06127074])

In [67]:
linear_ratio = np.array(range(1,11))
linear_ratio = linear_ratio / linear_ratio.max()
stats = np.unique(svhn_train.labels, return_counts=True)[1]
subset = stats.min() * linear_ratio
subset = subset.astype(int)
subset

array([ 465,  931, 1397, 1863, 2329, 2795, 3261, 3727, 4193, 4659])

In [68]:
sum(subset)

25620

### severe imbalance

In [94]:
num_of_class = 10
alpha=0.01
x = np.linspace(1, 5, num_of_class)
target = scipy.stats.genpareto.pdf(x, alpha).tolist()
severe_ratio = np.array([t/sum(target) for t in target])
severe_ratio = severe_ratio / max(severe_ratio)
stats = np.unique(svhn_train.labels, return_counts=True)[1]
subset = stats.min() * severe_ratio
subset = np.flip(subset.astype(int))

In [95]:
subset

array([  92,  141,  217,  335,  517,  799, 1238, 1922, 2990, 4659])